


keep-del-app "Clock FileManager KeKeThemeSpace"   #删除所有*/*del-app*/*  apps为要保留的
de KeKeMarket "软件商店"
de OTA "软件更新"
de Browser "浏览器"
de Music "音乐"
de update
de LinktoWindows "连接windows"
de OTA "软件更新"
de BrowserVideo "视频"
de SafeCenter "安全中心"

de VideoGallery "媒体播放器"
de AIUnit "AIUnit"
de KeKeAppDetail  "应用安装器  应用安装安全扫描"
de GlobalSearch "全局搜索"
de RomUpdate "更新服务"
de OTA "软件更新"

de AIUnit
de Aod "息屏显示"
de ChildrenSpace "儿童空间"
de FloatAssistant "悬浮球"
de HealthCheck
de Portrait "人像绘影"
de COSA "应用增强服务"
de OplusOperationManual "帮助与反馈"
de SceneMode "简易模式"
de HeyCast "手机投屏"
de OPSynergy "设备互联服务"


de iFlyIME "讯飞输入法"
de SogouInput* "搜狗输入法定制版"
de BaiduInput* "百度输入"
#de CarLink ""
de Pictorial "乐划锁屏"
de GmsCore "谷歌服务"
de OcrScanner "小布扫一扫"
de ColorDirectUI "小布识屏"
de ColorDirectService "识屏服务"
de HeyTapSpeechAssist "小布助手"
de Instant "快应用"
de *AccessoryFramework "设备快连"
de DCS "用户体验计划"
de dmp "融合搜索服务"
de OShare "一加互传"
de *EngineerCamera "一加工程相机"
#de OCar "车联"
de DigitalKeyFramework "数字车钥匙"
de ShareScreen "屏幕共享"
de OShare "一加互传"
de Calendar "日历"
de CalendarProvider "日历储存"
# de MSPService "移动服务"
de ViewTalk "图片描述"
de ColorAccessibilityAssistant "语音转文字"
de OVoiceManagerServiceOnePlus "语音唤醒 "
de HTMLViewer ""
de NetworkAssistSys "网络服务"
de UpgradeGuide "升级指南"
de CloudAccService "OPPO智慧云加速"
# de *SecurityKeyboard "安全键盘"
de WallpaperChooser "动态壁纸选择器"
de *TranslationService "翻译服务"
rm -rf */Omoji
de Omoji ""
de KeKePay "安全支付"
de SecurePay "安全支付"
de TasWallet "系统卡包"
de CloudService "云服务 "
de OWork "随身工作台"
de TravelEngine "智慧出行"
de AssistantScreen "速览"

de talkback* "安卓无障碍套件"
de SceneService "数据服务平台"
de SwitchAccess "google开关控制"
de HealthService "健康数据平台"
de DigitalWellBeing "数字健康"
de SupertextInput "扫描输入"
de UMS "服务治理框架"
de SOSHelper "SOS紧急联络"
# de FindMyPhone* "查找手机 "
de PhoneManager "手机管家"

de GoogleServicesFramework "谷歌服务框架"
de GooglePlayServicesUpdater ""
de *WeatherService "天气服务"
de olc ""
de PostmanService "诊断工具服务"
de LogKit "反馈工具箱"
de *EngineerMode "工程模式"
