name: Build OpenWrt

on: 
  watch:
    types: [started]
    
env:
  ssh: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
       
    - name: 获取源码&替换config
      run: |
        git clone https://github.com/ReFirmLabs/binwalk
        cd binwalk
        wget https://github.com/zhlhlf/text/blob/main/RT-AC1200HP-GPIO-12-JI3-128M_3.4.3.9-099.trx

    - name: ssh连接
      if: env.ssh == 'true'            
      uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}      
              
      
